export {default as AboutUs} from "./AboutUs"
export {default as Home} from "./Home"
export {default as Instructions} from "./Instructions"
export {default as VendingMachine} from "./VendingMachine"
export {default as Contact} from "./Contact"